# Generated by Django 4.2.16 on 2024-10-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.CharField(default='default_value', max_length=255, unique=True),
        ),
    ]
